"""empty message

Revision ID: 25d3a04ec9a3
Revises: 476cca6be3a9
Create Date: 2019-10-27 13:21:45.641413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25d3a04ec9a3'
down_revision = '476cca6be3a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genres', sa.ARRAY(sa.String(length=120)), nullable=True))
    op.add_column('Venue', sa.Column('past_shows', sa.ARRAY(sa.JSON()), nullable=True))
    op.add_column('Venue', sa.Column('past_shows_count', sa.Integer(), nullable=True))
    op.add_column('Venue', sa.Column('seeking_description', sa.String(length=500), nullable=True))
    op.add_column('Venue', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.add_column('Venue', sa.Column('upcoming_shows', sa.ARRAY(sa.JSON()), nullable=True))
    op.add_column('Venue', sa.Column('upcomint_shows_count', sa.Integer(), nullable=True))
    op.add_column('Venue', sa.Column('webstie', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'webstie')
    op.drop_column('Venue', 'upcomint_shows_count')
    op.drop_column('Venue', 'upcoming_shows')
    op.drop_column('Venue', 'seeking_talent')
    op.drop_column('Venue', 'seeking_description')
    op.drop_column('Venue', 'past_shows_count')
    op.drop_column('Venue', 'past_shows')
    op.drop_column('Venue', 'genres')
    # ### end Alembic commands ###
